Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'project#welcome'
  get '/start', to: 'project#index'
  post '/new_project', to: 'project#new_project'
  delete '/destroy_project/:projectId', to: 'project#destroy_project',as: 'destroy_project'
  get '/dashboard/:id', to: 'dashboard#index', as: 'dashboard'
  post '/move_to_sprint/:cardId/:boardId', to: 'card#move_to_sprint'
  post '/move_to_planned/:card_id', to: 'sprint_card#move_to_planned'
  post '/new_card', to: 'card#new_card'
  post '/add_user/:projectId/:userId', to: 'project#add_user'
  post '/rename/:id', to: 'card#rename'
  get 'sprint/:id', to: 'sprint#index', as: 'sprint'
  get '/change_sprint_board/:cardId/:board_title', to: 'sprint_card#change_board'
  get '/change_board/:cardId/:boardId', to: 'dashboard#change_board'
  post '/change_board_and_delete/:cardId/:boardId', to: 'dashboard#change_board_and_delete'
  post '/update_sprint_card/:id', to: 'sprint_card#update'
  post '/update_card/:id', to: 'card#update'
  post '/sprint_card_done/:cardId', to: 'sprint_card#done'
  get '/check_estimations/:cardId/:round_number', to: 'sprint_card#check_estimations'
  get '/check_comments/:cardId/:round_number', to: 'sprint_card#check_comments'
  get '/get_projects', to: 'project#get_projects'
  get '/get_cards/:board_id', to: 'dashboard#get_cards'
  get '/get_sprint_cards/:sprint_board_id', to: 'sprint#get_sprint_cards'
  get '/get_users/:project_id', to: 'project#get_users'
  get '/get_available_users/:project_id', to: 'project#get_available_users'
  post '/add_round/:card_id/:round_number', to: 'sprint_card#add_round'
  post '/add_card_round/:card_id/:round_number', to: 'card#add_card_round'
  get '/card_assets/:card_id', to: 'sprint_card#card_assets'
  get '/user_count/:project_id', to: 'project#user_count'
  get '/update_comments/:round_id', to: 'sprint_card#update_comments'
  post '/update_card_comments/:round_id', to: 'card#update_card_comments'
  post '/estimate/:card_id', to: 'sprint_card#estimate'
  post '/estimate_card/:card_id', to: 'card#estimate'
  get '/check_estimation_done/:card_id', to: 'sprint_card#check_estimation_done'
  post '/update_options/:card_id', to: 'sprint_card#update_options'
  post '/update_work_done/:card_id', to: 'sprint_card#update_work_done'
  get '/role_management', to: 'project#role_management', as: 'role'
  post '/change_role', to: 'project#change_role'
  post '/register_for_card/:card_id', to: 'sprint_card#register_for_card'
  post '/new_sprint_card', to: 'sprint_card#new_sprint_card'
  delete '/delete_sprint_card/:card_id', to: 'sprint_card#delete_sprint_card'
  delete '/delete_card/:card_id', to: 'card#delete_card'
  post '/update_request/:card_id', to: 'sprint_card#update_request'
  post '/update_prio', to: 'sprint_card#update_prio'
  get '/update_retro', to: 'sprint_card#update_retro'
  get '/render_charts', to: 'dashboard#render_charts'
  get '/assets/:card_id', to: 'card#assets'
  post '/update_card_options/:card_id', to: 'card#update_card_options'
  get '/render_sb', to: 'dashboard#render_sb'
end
